import { Hr, Link, Section, Text } from "@react-email/components"
import * as React from "react"

import {
  defaultEmailBranding,
  type EmailBranding,
} from "../brand.js"

export interface EmailFooterProps {
  branding?: Partial<EmailBranding>
  footerNote?: string
  helpUrl?: string
}

export function EmailFooter({
  branding,
  footerNote = "This message was generated by Ink Wave's shared email package.",
  helpUrl,
}: EmailFooterProps) {
  const resolvedBranding = { ...defaultEmailBranding, ...branding }

  return (
    <>
      <Hr className="my-8 border-border" />
      <Section>
        <Text className="m-0 text-sm font-semibold text-foreground">
          {resolvedBranding.companyName}
        </Text>
        <Text className="m-0 mt-2 text-sm leading-6 text-muted-foreground">
          {resolvedBranding.tagline}
        </Text>
        <Text className="m-0 mt-4 text-xs leading-5 text-muted-foreground">
          Support:{" "}
          <Link className="text-primary no-underline" href={`mailto:${resolvedBranding.supportEmail}`}>
            {resolvedBranding.supportEmail}
          </Link>
          {helpUrl ? (
            <>
              {" "}
              ·{" "}
              <Link className="text-primary no-underline" href={helpUrl}>
                Open dashboard
              </Link>
            </>
          ) : null}
        </Text>
        <Text className="m-0 mt-3 text-xs leading-5 text-muted-foreground">{footerNote}</Text>
      </Section>
    </>
  )
}
