/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as LoginRouteImport } from "./pages/login"
import { Route as AppRouteImport } from "./pages/_app"
import { Route as IndexRouteImport } from "./pages/index"
import { Route as AppReportsRouteImport } from "./pages/_app.reports"
import { Route as AppOrdersRouteImport } from "./pages/_app.orders"
import { Route as AppInventoryRouteImport } from "./pages/_app.inventory"
import { Route as AppDesignSystemRouteImport } from "./pages/_app.design-system"
import { Route as AppDashboardRouteImport } from "./pages/_app.dashboard"
import { Route as AppCupsRouteImport } from "./pages/_app.cups"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: "/inventory",
  path: "/inventory",
  getParentRoute: () => AppRoute,
} as any)
const AppDesignSystemRoute = AppDesignSystemRouteImport.update({
  id: "/design-system",
  path: "/design-system",
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRoute,
} as any)
const AppCupsRoute = AppCupsRouteImport.update({
  id: "/cups",
  path: "/cups",
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/cups": typeof AppCupsRoute
  "/dashboard": typeof AppDashboardRoute
  "/design-system": typeof AppDesignSystemRoute
  "/inventory": typeof AppInventoryRoute
  "/orders": typeof AppOrdersRoute
  "/reports": typeof AppReportsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/cups": typeof AppCupsRoute
  "/dashboard": typeof AppDashboardRoute
  "/design-system": typeof AppDesignSystemRoute
  "/inventory": typeof AppInventoryRoute
  "/orders": typeof AppOrdersRoute
  "/reports": typeof AppReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_app": typeof AppRouteWithChildren
  "/login": typeof LoginRoute
  "/_app/cups": typeof AppCupsRoute
  "/_app/dashboard": typeof AppDashboardRoute
  "/_app/design-system": typeof AppDesignSystemRoute
  "/_app/inventory": typeof AppInventoryRoute
  "/_app/orders": typeof AppOrdersRoute
  "/_app/reports": typeof AppReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/cups"
    | "/dashboard"
    | "/design-system"
    | "/inventory"
    | "/orders"
    | "/reports"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/cups"
    | "/dashboard"
    | "/design-system"
    | "/inventory"
    | "/orders"
    | "/reports"
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/login"
    | "/_app/cups"
    | "/_app/dashboard"
    | "/_app/design-system"
    | "/_app/inventory"
    | "/_app/orders"
    | "/_app/reports"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/reports": {
      id: "/_app/reports"
      path: "/reports"
      fullPath: "/reports"
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/orders": {
      id: "/_app/orders"
      path: "/orders"
      fullPath: "/orders"
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/inventory": {
      id: "/_app/inventory"
      path: "/inventory"
      fullPath: "/inventory"
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/design-system": {
      id: "/_app/design-system"
      path: "/design-system"
      fullPath: "/design-system"
      preLoaderRoute: typeof AppDesignSystemRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/dashboard": {
      id: "/_app/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/cups": {
      id: "/_app/cups"
      path: "/cups"
      fullPath: "/cups"
      preLoaderRoute: typeof AppCupsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCupsRoute: typeof AppCupsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDesignSystemRoute: typeof AppDesignSystemRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppReportsRoute: typeof AppReportsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCupsRoute: AppCupsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDesignSystemRoute: AppDesignSystemRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppReportsRoute: AppReportsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
