/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as LoginRouteImport } from "./pages/login"
import { Route as AppRouteImport } from "./pages/_app"
import { Route as IndexRouteImport } from "./pages/index"
import { Route as AppReportsRouteImport } from "./pages/_app.reports"
import { Route as AppOrdersRouteImport } from "./pages/_app.orders"
import { Route as AppLidsRouteImport } from "./pages/_app.lids"
import { Route as AppInvoicesRouteImport } from "./pages/_app.invoices"
import { Route as AppInventoryHistoryRouteImport } from "./pages/_app.inventory-history"
import { Route as AppInventoryRouteImport } from "./pages/_app.inventory"
import { Route as AppGeneralItemsRouteImport } from "./pages/_app.general-items"
import { Route as AppDesignSystemRouteImport } from "./pages/_app.design-system"
import { Route as AppDashboardRouteImport } from "./pages/_app.dashboard"
import { Route as AppCustomersRouteImport } from "./pages/_app.customers"
import { Route as AppCupsRouteImport } from "./pages/_app.cups"
import { Route as AppOrdersIndexRouteImport } from "./pages/_app.orders.index"
import { Route as AppInvoicesIndexRouteImport } from "./pages/_app.invoices.index"
import { Route as AppOrdersNewRouteImport } from "./pages/_app.orders.new"
import { Route as AppOrdersOrderIdRouteImport } from "./pages/_app.orders.$orderId"
import { Route as AppInvoicesInvoiceIdRouteImport } from "./pages/_app.invoices.$invoiceId"
import { Route as AppOrdersOrderIdIndexRouteImport } from "./pages/_app.orders.$orderId.index"
import { Route as AppOrdersOrderIdFulfillmentRouteImport } from "./pages/_app.orders.$orderId.fulfillment"
import { Route as AppOrdersOrderIdEditRouteImport } from "./pages/_app.orders.$orderId.edit"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => AppRoute,
} as any)
const AppLidsRoute = AppLidsRouteImport.update({
  id: "/lids",
  path: "/lids",
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: "/invoices",
  path: "/invoices",
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryHistoryRoute = AppInventoryHistoryRouteImport.update({
  id: "/inventory-history",
  path: "/inventory-history",
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: "/inventory",
  path: "/inventory",
  getParentRoute: () => AppRoute,
} as any)
const AppGeneralItemsRoute = AppGeneralItemsRouteImport.update({
  id: "/general-items",
  path: "/general-items",
  getParentRoute: () => AppRoute,
} as any)
const AppDesignSystemRoute = AppDesignSystemRouteImport.update({
  id: "/design-system",
  path: "/design-system",
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: "/customers",
  path: "/customers",
  getParentRoute: () => AppRoute,
} as any)
const AppCupsRoute = AppCupsRouteImport.update({
  id: "/cups",
  path: "/cups",
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: "/$orderId",
  path: "/$orderId",
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: "/$invoiceId",
  path: "/$invoiceId",
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppOrdersOrderIdIndexRoute = AppOrdersOrderIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppOrdersOrderIdRoute,
} as any)
const AppOrdersOrderIdFulfillmentRoute =
  AppOrdersOrderIdFulfillmentRouteImport.update({
    id: "/fulfillment",
    path: "/fulfillment",
    getParentRoute: () => AppOrdersOrderIdRoute,
  } as any)
const AppOrdersOrderIdEditRoute = AppOrdersOrderIdEditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => AppOrdersOrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/cups": typeof AppCupsRoute
  "/customers": typeof AppCustomersRoute
  "/dashboard": typeof AppDashboardRoute
  "/design-system": typeof AppDesignSystemRoute
  "/general-items": typeof AppGeneralItemsRoute
  "/inventory": typeof AppInventoryRoute
  "/inventory-history": typeof AppInventoryHistoryRoute
  "/invoices": typeof AppInvoicesRouteWithChildren
  "/lids": typeof AppLidsRoute
  "/orders": typeof AppOrdersRouteWithChildren
  "/reports": typeof AppReportsRoute
  "/invoices/$invoiceId": typeof AppInvoicesInvoiceIdRoute
  "/orders/$orderId": typeof AppOrdersOrderIdRouteWithChildren
  "/orders/new": typeof AppOrdersNewRoute
  "/invoices/": typeof AppInvoicesIndexRoute
  "/orders/": typeof AppOrdersIndexRoute
  "/orders/$orderId/edit": typeof AppOrdersOrderIdEditRoute
  "/orders/$orderId/fulfillment": typeof AppOrdersOrderIdFulfillmentRoute
  "/orders/$orderId/": typeof AppOrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/cups": typeof AppCupsRoute
  "/customers": typeof AppCustomersRoute
  "/dashboard": typeof AppDashboardRoute
  "/design-system": typeof AppDesignSystemRoute
  "/general-items": typeof AppGeneralItemsRoute
  "/inventory": typeof AppInventoryRoute
  "/inventory-history": typeof AppInventoryHistoryRoute
  "/lids": typeof AppLidsRoute
  "/reports": typeof AppReportsRoute
  "/invoices/$invoiceId": typeof AppInvoicesInvoiceIdRoute
  "/orders/new": typeof AppOrdersNewRoute
  "/invoices": typeof AppInvoicesIndexRoute
  "/orders": typeof AppOrdersIndexRoute
  "/orders/$orderId/edit": typeof AppOrdersOrderIdEditRoute
  "/orders/$orderId/fulfillment": typeof AppOrdersOrderIdFulfillmentRoute
  "/orders/$orderId": typeof AppOrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_app": typeof AppRouteWithChildren
  "/login": typeof LoginRoute
  "/_app/cups": typeof AppCupsRoute
  "/_app/customers": typeof AppCustomersRoute
  "/_app/dashboard": typeof AppDashboardRoute
  "/_app/design-system": typeof AppDesignSystemRoute
  "/_app/general-items": typeof AppGeneralItemsRoute
  "/_app/inventory": typeof AppInventoryRoute
  "/_app/inventory-history": typeof AppInventoryHistoryRoute
  "/_app/invoices": typeof AppInvoicesRouteWithChildren
  "/_app/lids": typeof AppLidsRoute
  "/_app/orders": typeof AppOrdersRouteWithChildren
  "/_app/reports": typeof AppReportsRoute
  "/_app/invoices/$invoiceId": typeof AppInvoicesInvoiceIdRoute
  "/_app/orders/$orderId": typeof AppOrdersOrderIdRouteWithChildren
  "/_app/orders/new": typeof AppOrdersNewRoute
  "/_app/invoices/": typeof AppInvoicesIndexRoute
  "/_app/orders/": typeof AppOrdersIndexRoute
  "/_app/orders/$orderId/edit": typeof AppOrdersOrderIdEditRoute
  "/_app/orders/$orderId/fulfillment": typeof AppOrdersOrderIdFulfillmentRoute
  "/_app/orders/$orderId/": typeof AppOrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/cups"
    | "/customers"
    | "/dashboard"
    | "/design-system"
    | "/general-items"
    | "/inventory"
    | "/inventory-history"
    | "/invoices"
    | "/lids"
    | "/orders"
    | "/reports"
    | "/invoices/$invoiceId"
    | "/orders/$orderId"
    | "/orders/new"
    | "/invoices/"
    | "/orders/"
    | "/orders/$orderId/edit"
    | "/orders/$orderId/fulfillment"
    | "/orders/$orderId/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/cups"
    | "/customers"
    | "/dashboard"
    | "/design-system"
    | "/general-items"
    | "/inventory"
    | "/inventory-history"
    | "/lids"
    | "/reports"
    | "/invoices/$invoiceId"
    | "/orders/new"
    | "/invoices"
    | "/orders"
    | "/orders/$orderId/edit"
    | "/orders/$orderId/fulfillment"
    | "/orders/$orderId"
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/login"
    | "/_app/cups"
    | "/_app/customers"
    | "/_app/dashboard"
    | "/_app/design-system"
    | "/_app/general-items"
    | "/_app/inventory"
    | "/_app/inventory-history"
    | "/_app/invoices"
    | "/_app/lids"
    | "/_app/orders"
    | "/_app/reports"
    | "/_app/invoices/$invoiceId"
    | "/_app/orders/$orderId"
    | "/_app/orders/new"
    | "/_app/invoices/"
    | "/_app/orders/"
    | "/_app/orders/$orderId/edit"
    | "/_app/orders/$orderId/fulfillment"
    | "/_app/orders/$orderId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/reports": {
      id: "/_app/reports"
      path: "/reports"
      fullPath: "/reports"
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/orders": {
      id: "/_app/orders"
      path: "/orders"
      fullPath: "/orders"
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/lids": {
      id: "/_app/lids"
      path: "/lids"
      fullPath: "/lids"
      preLoaderRoute: typeof AppLidsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/invoices": {
      id: "/_app/invoices"
      path: "/invoices"
      fullPath: "/invoices"
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/inventory-history": {
      id: "/_app/inventory-history"
      path: "/inventory-history"
      fullPath: "/inventory-history"
      preLoaderRoute: typeof AppInventoryHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/inventory": {
      id: "/_app/inventory"
      path: "/inventory"
      fullPath: "/inventory"
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/general-items": {
      id: "/_app/general-items"
      path: "/general-items"
      fullPath: "/general-items"
      preLoaderRoute: typeof AppGeneralItemsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/design-system": {
      id: "/_app/design-system"
      path: "/design-system"
      fullPath: "/design-system"
      preLoaderRoute: typeof AppDesignSystemRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/dashboard": {
      id: "/_app/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/customers": {
      id: "/_app/customers"
      path: "/customers"
      fullPath: "/customers"
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/cups": {
      id: "/_app/cups"
      path: "/cups"
      fullPath: "/cups"
      preLoaderRoute: typeof AppCupsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/orders/": {
      id: "/_app/orders/"
      path: "/"
      fullPath: "/orders/"
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    "/_app/invoices/": {
      id: "/_app/invoices/"
      path: "/"
      fullPath: "/invoices/"
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    "/_app/orders/new": {
      id: "/_app/orders/new"
      path: "/new"
      fullPath: "/orders/new"
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    "/_app/orders/$orderId": {
      id: "/_app/orders/$orderId"
      path: "/$orderId"
      fullPath: "/orders/$orderId"
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    "/_app/invoices/$invoiceId": {
      id: "/_app/invoices/$invoiceId"
      path: "/$invoiceId"
      fullPath: "/invoices/$invoiceId"
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    "/_app/orders/$orderId/": {
      id: "/_app/orders/$orderId/"
      path: "/"
      fullPath: "/orders/$orderId/"
      preLoaderRoute: typeof AppOrdersOrderIdIndexRouteImport
      parentRoute: typeof AppOrdersOrderIdRoute
    }
    "/_app/orders/$orderId/fulfillment": {
      id: "/_app/orders/$orderId/fulfillment"
      path: "/fulfillment"
      fullPath: "/orders/$orderId/fulfillment"
      preLoaderRoute: typeof AppOrdersOrderIdFulfillmentRouteImport
      parentRoute: typeof AppOrdersOrderIdRoute
    }
    "/_app/orders/$orderId/edit": {
      id: "/_app/orders/$orderId/edit"
      path: "/edit"
      fullPath: "/orders/$orderId/edit"
      preLoaderRoute: typeof AppOrdersOrderIdEditRouteImport
      parentRoute: typeof AppOrdersOrderIdRoute
    }
  }
}

interface AppInvoicesRouteChildren {
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppOrdersOrderIdRouteChildren {
  AppOrdersOrderIdEditRoute: typeof AppOrdersOrderIdEditRoute
  AppOrdersOrderIdFulfillmentRoute: typeof AppOrdersOrderIdFulfillmentRoute
  AppOrdersOrderIdIndexRoute: typeof AppOrdersOrderIdIndexRoute
}

const AppOrdersOrderIdRouteChildren: AppOrdersOrderIdRouteChildren = {
  AppOrdersOrderIdEditRoute: AppOrdersOrderIdEditRoute,
  AppOrdersOrderIdFulfillmentRoute: AppOrdersOrderIdFulfillmentRoute,
  AppOrdersOrderIdIndexRoute: AppOrdersOrderIdIndexRoute,
}

const AppOrdersOrderIdRouteWithChildren =
  AppOrdersOrderIdRoute._addFileChildren(AppOrdersOrderIdRouteChildren)

interface AppOrdersRouteChildren {
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRouteWithChildren
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersOrderIdRoute: AppOrdersOrderIdRouteWithChildren,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppRouteChildren {
  AppCupsRoute: typeof AppCupsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDesignSystemRoute: typeof AppDesignSystemRoute
  AppGeneralItemsRoute: typeof AppGeneralItemsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInventoryHistoryRoute: typeof AppInventoryHistoryRoute
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppLidsRoute: typeof AppLidsRoute
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCupsRoute: AppCupsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDesignSystemRoute: AppDesignSystemRoute,
  AppGeneralItemsRoute: AppGeneralItemsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInventoryHistoryRoute: AppInventoryHistoryRoute,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppLidsRoute: AppLidsRoute,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
